#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=tests/test-lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/test-lib.sh"

new_test_home
trap cleanup_test_home EXIT

declare -A targets=(
  [claude]="$HOME/.claude/CLAUDE.md"
  [codex]="$HOME/.codex/AGENTS.md"
  [kimi]="$HOME/.kimi-code/AGENTS.md"
  [opencode]="$HOME/.config/opencode/AGENTS.md"
)

for harness in claude codex kimi opencode; do
  "$TEST_ROOT/install.sh" --only "$harness"
  target="${targets[$harness]}"
  assert_file "$target"
  grep -q '^<!-- Generated by agent-config; edit instructions/common.md or the harness overlay\. -->$' "$target"
  grep -q 'Toujours tutoyer Cyril' "$target"
  cmp -s \
    <(sed '1,/^$/d' "$target") \
    <(printf '%s\n\n' "$(cat "$TEST_ROOT/instructions/common.md")"; cat "$TEST_ROOT/harnesses/$harness/instructions.overlay.md") || {
      printf 'rendered instructions differ for %s\n' "$harness" >&2
      exit 1
    }
done

"$TEST_ROOT/install.sh" --check

printf '\nmanual drift\n' >>"${targets[codex]}"
if "$TEST_ROOT/install.sh" --check --only codex >"$TEST_TMP/check.out" 2>&1; then
  printf '%s\n' '--check accepted instruction drift' >&2
  exit 1
fi
grep -q "DRIFT codex ${targets[codex]} content" "$TEST_TMP/check.out"

"$TEST_ROOT/install.sh" --only codex
printf '%s\n' 'residual hub instructions' >"$HOME/.agents/AGENTS.md"
before_hash="$(sha256sum "$HOME/.agents/AGENTS.md" | awk '{print $1}')"
if "$TEST_ROOT/install.sh" --check >"$TEST_TMP/hub-check.out" 2>&1; then
  printf '%s\n' '--check accepted ~/.agents/AGENTS.md' >&2
  exit 1
fi
grep -q "DRIFT shared $HOME/.agents/AGENTS.md unexpected" "$TEST_TMP/hub-check.out"
after_hash="$(sha256sum "$HOME/.agents/AGENTS.md" | awk '{print $1}')"
[ "$before_hash" = "$after_hash" ]

dry_home="$TEST_TMP/dry-home"
mkdir -p "$dry_home"
HOME="$dry_home" AGENT_CONFIG_WINDOWS_CODEX_DIR='' AGENT_CONFIG_SKIP_PLUGINS=1 \
  "$TEST_ROOT/install.sh" --dry-run --only claude >"$TEST_TMP/dry.out"
[ -z "$(find "$dry_home" -mindepth 1 -print -quit)" ]
grep -q '^WOULD ' "$TEST_TMP/dry.out"

if "$TEST_ROOT/install.sh" --only unknown >"$TEST_TMP/unknown.out" 2>&1; then
  printf '%s\n' 'unknown harness was accepted' >&2
  exit 1
fi
grep -q 'unknown harness: unknown' "$TEST_TMP/unknown.out"

printf 'instruction tests: PASS\n'
